# Generated by Django 4.2.9 on 2024-03-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_id', models.CharField(max_length=128)),
                ('stream_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('user_login', models.CharField(max_length=128)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('url', models.TextField()),
                ('thumbnail_url', models.TextField()),
                ('viewable', models.CharField(max_length=64)),
                ('view_count', models.IntegerField()),
                ('language', models.CharField(max_length=32)),
                ('vod_type', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
            ],
        ),
    ]
