# Generated by Django 4.2.9 on 2024-03-14 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveatfive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchvideo',
            name='user_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='duration',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='language',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='stream_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='thumbnail_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='user_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='user_login',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='viewable',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='vod_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitchvideo',
            name='vod_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
