# Generated by Django 4.2.9 on 2024-03-15 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveatfive', '0002_twitchvideo_user_name_alter_twitchvideo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamInfo',
            fields=[
                ('date', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='start time')),
                ('offset', models.FloatField(default=0.0)),
                ('punctuality', models.IntegerField(choices=[(0, 'Early'), (1, 'On time'), (2, 'Late')], default=2)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6)),
            ],
        ),
    ]
