# Generated by Django 4.2.9 on 2024-03-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveatfive', '0003_streaminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorInfo',
            fields=[
                ('creator_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('is_live', models.BooleanField(default=False)),
                ('was_live', models.BooleanField(default=False)),
            ],
        ),
    ]
