# Generated by Django 4.2.9 on 2024-03-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveatfive', '0004_creatorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorinfo',
            name='average_offset',
            field=models.FloatField(default=0.0),
        ),
    ]
